---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ecommstoredeploy
spec:
 replicas: 2
 strategy: 
  type: RollingUpdate
 selector:
  matchLabels:
   app: ecommstore
 template:
  metadata:
   name: ecommstore
   labels:
    app: ecommstore
  spec:
   containers:
   - name: ecommstorecontainer
     image: richard92/ecommerce
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: ecommstoresvc
spec:
 type: LoadBalancer
 selector:
  app: ecommstore
 ports:
  - port: 80
    targetPort: 80
...
